In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [3]:
from keras import Sequential
from keras.layers import Dense, SimpleRNN

In [6]:
model = Sequential()
model.add(SimpleRNN(3,input_shape=(4,5)))
model.add(Dense(1,activation='sigmoid'))
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_2 (SimpleRNN)        │ (None, 3)              │            27 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 31 (124.00 B)

 Trainable params: 31 (124.00 B)

 Non-trainable params: 0 (0.00 B)

In [9]:
print(model.get_weights()[0].shape)
model.get_weights()[0]

(5, 3)


array([[ 0.48194045,  0.7428214 ,  0.7702896 ],
       [-0.71936303,  0.11797988, -0.63814753],
       [ 0.5371644 , -0.26653105, -0.33044487],
       [-0.7257618 ,  0.82463115, -0.561571  ],
       [ 0.2988804 , -0.06250066,  0.329817  ]], dtype=float32)

In [10]:
print(model.get_weights()[1].shape)
model.get_weights()[1]

(3, 3)


array([[ 0.0446614 , -0.25604403,  0.9656328 ],
       [-0.9598799 , -0.2788508 , -0.02954382],
       [ 0.276832  , -0.92557204, -0.25822553]], dtype=float32)

In [11]:
print(model.get_weights()[2].shape)
model.get_weights()[2]

(3,)


array([0., 0., 0.], dtype=float32)

In [12]:
print(model.get_weights()[3].shape)
model.get_weights()[3]

(3, 1)


array([[ 0.996678  ],
       [-0.30210346],
       [ 0.7358303 ]], dtype=float32)

In [13]:
print(model.get_weights()[4].shape)
model.get_weights()[4]

(1,)


array([0.], dtype=float32)

IndexError: list index out of range